export const ActionTypes = {
  CREATE_BLOG : 'CREATE_BLOG',

  ALL_USERS : 'ALL_USERS',
  LOG_IN : 'LOG_IN',
  LOG_OUT : 'LOG_OUT',

  INITIAL_BLOGS : 'INITIAL_BLOGS',
  REMOVE_BLOG : 'REMOVE_BLOG',
  LIKE_BLOG: 'LIKE_BLOG',

  SET_NOTIFICATION : 'SET_NOTIFICATION',
  REMOVE_NOTIFICATION : 'REMOVE_NOTIFICATION'
}